/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'ppf' : IDL.Null,
  'carAccessories' : IDL.Null,
  'polishing' : IDL.Null,
  'bikeWash' : IDL.Null,
  'carWashing' : IDL.Null,
  'detailing' : IDL.Null,
  'wrapping' : IDL.Null,
  'windowFilm' : IDL.Null,
  'ceramicCoating' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'service' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingById' : IDL.Func([IDL.Text], [Booking], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'ppf' : IDL.Null,
    'carAccessories' : IDL.Null,
    'polishing' : IDL.Null,
    'bikeWash' : IDL.Null,
    'carWashing' : IDL.Null,
    'detailing' : IDL.Null,
    'wrapping' : IDL.Null,
    'windowFilm' : IDL.Null,
    'ceramicCoating' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'service' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingById' : IDL.Func([IDL.Text], [Booking], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };