/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Booking {
    id: string;
    service: ServiceType;
    name: string;
    email: string;
    message: string;
    preferredDate: string;
    timestamp: Time;
    phone: string;
}
export type Time = bigint;
export enum ServiceType {
    ppf = "ppf",
    carAccessories = "carAccessories",
    polishing = "polishing",
    bikeWash = "bikeWash",
    carWashing = "carWashing",
    detailing = "detailing",
    wrapping = "wrapping",
    windowFilm = "windowFilm",
    ceramicCoating = "ceramicCoating"
}
export interface backendInterface {
    getAllBookings(): Promise<Array<Booking>>;
    getBookingById(id: string): Promise<Booking>;
    submitBooking(name: string, email: string, phone: string, service: ServiceType, preferredDate: string, message: string): Promise<string>;
}
import type { Booking as _Booking, ServiceType as _ServiceType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_Booking_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_Booking_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitBooking(arg0: string, arg1: string, arg2: string, arg3: ServiceType, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0, arg1, arg2, to_candid_ServiceType_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0, arg1, arg2, to_candid_ServiceType_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_Booking_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    service: _ServiceType;
    name: string;
    email: string;
    message: string;
    preferredDate: string;
    timestamp: _Time;
    phone: string;
}): {
    id: string;
    service: ServiceType;
    name: string;
    email: string;
    message: string;
    preferredDate: string;
    timestamp: Time;
    phone: string;
} {
    return {
        id: value.id,
        service: from_candid_ServiceType_n4(_uploadFile, _downloadFile, value.service),
        name: value.name,
        email: value.email,
        message: value.message,
        preferredDate: value.preferredDate,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ppf: null;
} | {
    carAccessories: null;
} | {
    polishing: null;
} | {
    bikeWash: null;
} | {
    carWashing: null;
} | {
    detailing: null;
} | {
    wrapping: null;
} | {
    windowFilm: null;
} | {
    ceramicCoating: null;
}): ServiceType {
    return "ppf" in value ? ServiceType.ppf : "carAccessories" in value ? ServiceType.carAccessories : "polishing" in value ? ServiceType.polishing : "bikeWash" in value ? ServiceType.bikeWash : "carWashing" in value ? ServiceType.carWashing : "detailing" in value ? ServiceType.detailing : "wrapping" in value ? ServiceType.wrapping : "windowFilm" in value ? ServiceType.windowFilm : "ceramicCoating" in value ? ServiceType.ceramicCoating : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    ppf: null;
} | {
    carAccessories: null;
} | {
    polishing: null;
} | {
    bikeWash: null;
} | {
    carWashing: null;
} | {
    detailing: null;
} | {
    wrapping: null;
} | {
    windowFilm: null;
} | {
    ceramicCoating: null;
} {
    return value == ServiceType.ppf ? {
        ppf: null
    } : value == ServiceType.carAccessories ? {
        carAccessories: null
    } : value == ServiceType.polishing ? {
        polishing: null
    } : value == ServiceType.bikeWash ? {
        bikeWash: null
    } : value == ServiceType.carWashing ? {
        carWashing: null
    } : value == ServiceType.detailing ? {
        detailing: null
    } : value == ServiceType.wrapping ? {
        wrapping: null
    } : value == ServiceType.windowFilm ? {
        windowFilm: null
    } : value == ServiceType.ceramicCoating ? {
        ceramicCoating: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
